<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423203941 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE app_user_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE job_application_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE job_offer_id_seq CASCADE');
        $this->addSql('CREATE TABLE gallery (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, category VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, position INT NOT NULL, is_published BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE gallery_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, caption VARCHAR(255) DEFAULT NULL, position INT NOT NULL, gallery_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_21A0D47C4E7AF8F ON gallery_image (gallery_id)');
        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, filename VARCHAR(255) DEFAULT NULL, youtube_url VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, position INT NOT NULL, is_published BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE gallery_image ADD CONSTRAINT FK_21A0D47C4E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_application DROP CONSTRAINT fk_3e8af7dda76ed395');
        $this->addSql('ALTER TABLE job_application DROP CONSTRAINT fk_3e8af7ddc58d3b1e');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE job_application');
        $this->addSql('DROP TABLE job_offer');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE app_user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE job_application_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE job_offer_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_88bdf3e9e7927c74 ON app_user (email)');
        $this->addSql('CREATE TABLE job_application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, job_offer_id INT NOT NULL, status VARCHAR(20) NOT NULL, applied_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_c737c6883481d195 ON job_application (job_offer_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_job_application_user_job ON job_application (user_id, job_offer_id)');
        $this->addSql('CREATE INDEX idx_c737c688a76ed395 ON job_application (user_id)');
        $this->addSql('CREATE TABLE job_offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source VARCHAR(20) NOT NULL, external_id VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, location VARCHAR(255) DEFAULT NULL, url VARCHAR(1024) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE job_application ADD CONSTRAINT fk_3e8af7dda76ed395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE job_application ADD CONSTRAINT fk_3e8af7ddc58d3b1e FOREIGN KEY (job_offer_id) REFERENCES job_offer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gallery_image DROP CONSTRAINT FK_21A0D47C4E7AF8F');
        $this->addSql('DROP TABLE gallery');
        $this->addSql('DROP TABLE gallery_image');
        $this->addSql('DROP TABLE media');
    }
}
